regex:
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
validates:
  name_max_length: 50
  email_max_length: 255
  password_min_length: 6
avatar:
  size_default: 80
  index_page: 50
pagination:
  item_per_page: 10
